<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\MasterPemeriksaanFisikSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Master Pemeriksaan Fisiks';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="master-pemeriksaan-fisik-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Master Pemeriksaan Fisik', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); 
    ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'id_m_pemeriksaan_fisik',
            'no_rekam_medik',
            // 'tanda_vital',
            'tanda_vital_nadi',
            'tanda_vital_pernapasan',
            'tanda_vital_tekanan_darah',
            'tanda_vital_suhu_badan',
            //'status_gizi',
            'status_gizi_tinggi_badan',
            'status_gizi_berat_badan',
            'status_gizi_lingkaran_perut',
            'status_gizi_lingkaran_pinggang',
            // 'status_gizi_bentuk_badan',
            // 'status_gizi_imt',
            //'tingkat_kesadaran',
            // 'tingkat_kesadaran_kesadaran',
            // 'tingkat_kesadaran_kualitas_kontak',
            // 'tingkat_kesadaran_tampak_kesakitan',
            // 'tingkat_kesadaran_gangguan_saat_berjalan',
            //'kelenjar_getah_bening',
            //'kelenjar_getah_bening_leher',
            //'kelenjar_getah_bening_sub_mandibula',
            //'kelenjar_getah_bening_ketiak',
            //'kelenjar_getah_bening_inguinal',
            //'kepala',
            //'kepala_tulang',
            //'kepala_kulit_kepala',
            //'kepala_rambut',
            //'kepala_bentuk_wajah',
            //'mata',
            //'mata_persepsi_warna_kanan',
            //'mata_persepsi_warna_kiri',
            //'mata_kelopak_mata_kanan',
            //'mata_kelopak_mata_kiri',
            //'mata_konjungtiva_kanan',
            //'mata_konjungtiva_kiri',
            //'mata_gerak_bola_mata_kanan',
            //'mata_gerak_bola_mata_kiri',
            //'mata_sklera_kanan',
            //'mata_sklera_kiri',
            //'mata_lensa_mata_kanan',
            //'mata_lensa_mata_kiri',
            //'mata_kornea_kanan',
            //'mata_kornea_kiri',
            //'mata_bulu_mata_kanan',
            //'mata_bulu_mata_kiri',
            //'mata_tekanan_bola_mata_kanan',
            //'mata_tekanan_bola_mata_kiri',
            //'mata_penglihatan_3dimensi_kanan',
            //'mata_penglihatan_3dimensi_kiri',
            //'mata_visus_tanpa_koreksi',
            //'mata_visus_dengan_koreksi',
            //'telinga',
            //'telinga_daun_telinga_kanan',
            //'telinga_daun_telinga_kiri',
            //'telinga_liang_telinga_kanan',
            //'telinga_liang_telinga_kiri',
            //'telinga_serumen_kanan',
            //'telinga_serumen_kiri',
            //'telinga_test_berbisik_kanan',
            //'telinga_test_berbisik_kiri',
            //'telinga_tes_garpu_tala_kanan',
            //'telinga_tes_garpu_tala_kiri',
            //'telinga_weber_kanan',
            //'telinga_weber_kiri',
            //'telinga_swabach_kanan',
            //'telinga_swabach_kiri',
            //'telinga_bing_kanan',
            //'telinga_bing_kiri',
            //'telinga_lainnya',
            //'hidung',
            //'hidung_meatus_nasi',
            //'hidung_septum_nasi',
            //'hidung_konka_nasal',
            //'hidung_nyeri_ketok_sinus',
            //'hidung_penciuman',
            //'mulut',
            //'mulut_bibir',
            //'mulut_lidah',
            //'mulut_gusi',
            //'mulut_lainnya',
            //'gigi:ntext',
            //'gigi_missing',
            //'gigi_caries',
            //'gigi_tambahan',
            //'gigi_sisa_akar',
            //'tenggorokan',
            //'tenggorokan_pharynx',
            //'tenggorokan_tonsil_kanan',
            //'tenggorokan_tonsil_kiri',
            //'tenggorokan_tonsil_ukuran_kanan',
            //'tenggorokan_tonsil_ukuran_kiri',
            //'tenggorokan_palatum',
            //'tenggorokan_lainn',
            //'dada',
            //'dada_bentuk',
            //'dada_mamae',
            //'dada_tumor_ukuran',
            //'dada_tumor_letak',
            //'dada_tumor_konsisten',
            //'dada_lainnya',
            //'paru',
            //'paru_jantung_palpasi',
            //'paru_jantung_perkusi_kanan',
            //'paru_jantung_perkusi_kiri',
            //'paru_jantung_perkusi_iktus_kanan',
            //'paru_jantung_perkusi_iktus_kiri',
            //'paru_jantung_perkusi_iktus_kiri_sebut',
            //'paru_jantung_perkusi_batas_jantung_kanan',
            //'paru_jantung_perkusi_batas_jantung_kiri',
            //'paru_jantung_perkusi_batas_jantung_kiri_sebut',
            //'paru_jantung_auskultasi_bunyi_nafas_kanan',
            //'paru_jantung_auskultasi_bunyi_nafas_kiri',
            //'paru_jantung_auskultasi_bunyi_nafas_tambah_kanan',
            //'paru_jantung_auskultasi_bunyi_nafas_tambah_kiri',
            //'paru_jantung_bunyi_jantung',
            //'paru_jantung_bunyi_jantung_kiri',
            //'abdomen',
            //'abdomen_inspeksi',
            //'abdomen_perkusi',
            //'abdomen_auskultasi_bising_usus',
            //'abdomen_hati',
            //'abdomen_limpa',
            //'abdomen_ginjal_kanan',
            //'abdomen_ginjal_kiri',
            //'abdomen_ballotement_kanan',
            //'abdomen_ballotement_kiri',
            //'abdomen_nyeri_costo_vertebrae_kanan',
            //'abdomen_nyeri_costo_vertebrae_kiri',
            //'genitourinaria',
            //'genitourinaria_kandung_kemih',
            //'genitourinaria_anus',
            //'genitourinaria_genitalia_eksternal',
            //'genitourinaria_prostat',
            //'vertebra',
            //'vertebra_lainnya',
            //'tulang_atas',
            //'tulang_atas_simetris',
            //'tulang_atas_gerakan_abduksi_neer_kanan',
            //'tulang_atas_gerakan_abduksi_neer_kiri',
            //'tulang_atas_gerakan_abduksi_hawkin_kanan',
            //'tulang_atas_gerakan_abduksi_hawkin_kiri',
            //'tulang_atas_gerakan_drop_arm_kanan',
            //'tulang_atas_gerakan_drop_arm_kiri',
            //'tulang_atas_gerakan_yergason_kanan',
            //'tulang_atas_gerakan_yergason_kiri',
            //'tulang_atas_gerakan_speed_kanan',
            //'tulang_atas_gerakan_speed_kiri',
            //'tulang_atas_tulang_kanan',
            //'tulang_atas_tulang_kiri',
            //'tulang_atas_sensibilitas_kanan',
            //'tulang_atas_sensibilitas_kiri',
            //'tulang_atas_oedem_kanan',
            //'tulang_atas_oedem_kiri',
            //'tulang_atas_varises_kanan',
            //'tulang_atas_varises_kiri',
            //'tulang_atas_kekuatan_otot_pin_prick_kanan',
            //'tulang_atas_kekuatan_otot_pin_prick_kiri',
            //'tulang_atas_kekuatan_otot_phallent_kanan',
            //'tulang_atas_kekuatan_otot_phallent_kiri',
            //'tulang_atas_kekuatan_otot_tinnel_kanan',
            //'tulang_atas_kekuatan_otot_tinnel_kiri',
            //'tulang_atas_kekuatan_otot_finskelstein_kanan',
            //'tulang_atas_kekuatan_otot_finskelstein_kiri',
            //'tulang_atas_vaskularisasi_kanan',
            //'tulang_atas_vaskularisasi_kiri',
            //'tulang_atas_kelaianan_kukujari_kanan',
            //'tulang_atas_kelaianan_kukujari_kiri',
            //'tulang_bawah',
            //'tulang_bawah_simetris',
            //'tulang_bawah_laseque_kanan',
            //'tulang_bawah_laseque_kiri',
            //'tulang_bawah_kernique_kanan',
            //'tulang_bawah_kernique_kiri',
            //'tulang_bawah_patrick_kanan',
            //'tulang_bawah_patrick_kiri',
            //'tulang_bawah_contrapatrick_kanan',
            //'tulang_bawah_contrapatrick_kiri',
            //'tulang_bawah_nyeri_tekanan_kanan',
            //'tulang_bawah_nyeri_tekanan_kiri',
            //'tulang_bawah_kekuatan_otot_kanan',
            //'tulang_bawah_kekuatan_otot_kiri',
            //'tulang_bawah_sensibilitas_kanan',
            //'tulang_bawah_sensibilitas_kiri',
            //'tulang_bawah_oedema_kanan',
            //'tulang_bawah_oedema_kiri',
            //'tulang_bawah_varises_kanan',
            //'tulang_bawah_varises_kiri',
            //'tulang_bawah_vaskularisasi_kanan',
            //'tulang_bawah_vaskularisasi_kiri',
            //'tulang_bawah_kelainan_kuku_kanan',
            //'tulang_bawah_kelainan_kuku_kiri',
            //'otot_motorik',
            //'otot_motorik_trofi_kanan',
            //'otot_motorik_trofi_kiri',
            //'otot_motorik_tonus_kanan',
            //'otot_motorik_tonus_kiri',
            //'otot_motorik_gerakan_abnormal_kanan',
            //'otot_motorik_gerakan_abnormal_kiri',
            //'fungsi_sensorik',
            //'fungsi_sensorik_kanan',
            //'fungsi_sensorik_kiri',
            //'fungsi_autonom_kanan',
            //'fungsi_autonom_kiri',
            //'saraf',
            //'saraf_daya_ingat_segera',
            //'saraf_daya_ingat_jangka_menengah',
            //'saraf_daya_ingat_jangka_pendek',
            //'saraf_daya_ingat_jangka_panjang',
            //'saraf_orientasi_waktu',
            //'saraf_orientasi_orang',
            //'saraf_orientasi_tempat',
            //'saraf_kesan',
            //'saraf_kesan_n_i',
            //'saraf_kesan_n_ii',
            //'saraf_kesan_n_iii',
            //'saraf_kesan_n_iv',
            //'saraf_kesan_n_v',
            //'saraf_kesan_n_vi',
            //'saraf_kesan_n_vii',
            //'saraf_kesan_n_viii',
            //'saraf_kesan_n_ix',
            //'saraf_kesan_n_x',
            //'saraf_kesan_n_xi',
            //'saraf_kesan_n_xii',
            //'reflek',
            //'reflek_fisiologis_patella_kanan',
            //'reflek_fisiologis_patella_kiri',
            //'reflek_patologis_kanan',
            //'reflek_patologis_kiri',
            //'kulit',
            //'kulit_kulit',
            //'kulit_selaput_lendir',
            //'kulit_kuku',
            //'kulit_lain:ntext',
            //'kulit_lokasi',
            //'hasil_pemeriksaan_fisik_khusus',
            //'hasil_pemeriksaan_fisik_khusus_wawancara_psikiatri',
            //'hasil_pemeriksaan_fisik_khusus_narkoba_opiat',
            //'hasil_pemeriksaan_fisik_khusus_narkoba_stimulan',
            //'hasil_pemeriksaan_fisik_khusus_narkoba_barbiburat',
            //'resume_kelainan:ntext',
            //'hasil_body_map:ntext',
            //'hasil_brief_survey:ntext',
            //'diagnosis_kerja:ntext',
            //'diagnosis_diferensial:ntext',
            //'kategori_kesehatan:ntext',
            //'id_dokter_pemeriksaan_fisik',
            //'leher',
            //'leher_gerakan_leher',
            //'leher_otot_leher',
            //'leher_kelenjar_thyroid',
            //'leher_pulsasi_carotis',
            //'leher_tekanan_vena_jugularis',
            //'leher_trachea',
            //'leher_lainnya',
            //'is_verified',
            //'kulit_tato',
            //'telinga_audiometri_kanan',
            //'telinga_audiometri_kiri',
            //'telinga_timpani_kanan',
            //'telinga_timpani_kiri',
            //'icdt10',

            [
                'class' => 'app\components\ActionColumn',
            ],
        ],
        'pager' => [
            'class' => 'app\components\GridPager',
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>