-- mcu.spesialis_tht definition

-- Drop table

-- DROP TABLE mcu.spesialis_tht;

CREATE TABLE mcu.spesialis_tht (
	id_spesialis_tht serial NOT NULL,
	no_rekam_medik varchar(120) NOT NULL,
	no_daftar varchar NULL,
	created_at timestamp NULL,
	updated_at timestamp NULL,
	created_by int4 NULL,
	updated_by int4 NULL,
	tl_daun_telinga_kanan varchar(70) NULL,
	tl_daun_telinga_kiri varchar(70) NULL,
	tl_liang_telinga_kanan varchar(70) NULL,
	tl_liang_telinga_kiri varchar(70) NULL,
	tl_serumen_telinga_kanan varchar(70) NULL,
	tl_serumen_telinga_kiri varchar(70) NULL,
	tl_membrana_timpani_telinga_kanan varchar(70) NULL,
	tl_membrana_timpani_telinga_kiri varchar(70) NULL,
	tl_test_berbisik_telinga_kanan varchar(70) NULL,
	tl_test_berbisik_telinga_kiri varchar(70) NULL,
	tl_test_berbisik_telinga_kanan_6 varchar(70) NULL,
	tl_test_berbisik_telinga_kiri_6 varchar(70) NULL,
	tl_test_berbisik_telinga_kanan_4 varchar(70) NULL,
	tl_test_berbisik_telinga_kiri_4 varchar(70) NULL,
	tl_test_berbisik_telinga_kanan_3 varchar(70) NULL,
	tl_test_berbisik_telinga_kiri_3 varchar(70) NULL,
	tl_test_berbisik_telinga_kanan_1 varchar(70) NULL,
	tl_test_berbisik_telinga_kiri_1 varchar(70) NULL,
	tl_test_garpu_tala_rinne_telinga_kanan varchar(70) NULL,
	tl_test_garpu_tala_rinne_telinga_kiri varchar(70) NULL,
	tl_weber_telinga_kanan varchar(70) NULL,
	tl_weber_telinga_kiri varchar(70) NULL,
	tl_swabach_telinga_kanan varchar(70) NULL,
	tl_swabach_telinga_kiri varchar(70) NULL,
	tl_bing_telinga_kanan varchar(70) NULL,
	tl_bing_telinga_kiri varchar(70) NULL,
	tl_lain_lain varchar(70) NULL,
	hd_meatus_nasi varchar(70) NULL,
	hd_septum_nasi varchar(70) NULL,
	hd_septum_nasi_lainnya varchar(70) NULL,
	hd_konka_nasal varchar(70) NULL,
	hd_konka_nasal_lainnya varchar(70) NULL,
	hd_nyeri_ketok_sinus_maksilar varchar(70) NULL,
	hd_nyeri_ketok_sinus_maksilar_lainnya varchar(70) NULL,
	hd_penciuman varchar(70) NULL,
	hd_lain_lain varchar(70) NULL,
	tg_pharynx varchar(70) NULL,
	tg_tonsil_kanan varchar(70) NULL,
	tg_tonsil_kiri varchar(70) NULL,
	tg_ukuran_kanan varchar(70) NULL,
	tg_ukuran_kiri varchar(70) NULL,
	tg_palatum varchar(70) NULL,
	tg_lain_lain varchar(70) NULL,
	audiometri text NULL,
	kesimpulan text NULL,
	riwayat text NULL,
	kesan text NULL,
	status_pemeriksaan text NULL,
	CONSTRAINT spesialis_tht_pkey PRIMARY KEY (id_spesialis_tht)
);